version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - media_volume:/app/media
    env_file:
      - ./backend/.env.prod
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env.prod.db
  nginx:
    build:
      context: ./backend/nginx
    ports:
      - "4000:4000"
    volumes:
      - media_volume:/app/media
    depends_on:
      - frontend
      - backend

volumes:
  media_volume:
  postgres_data:
