# Generated by Django 4.2.4 on 2023-08-19 06:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('linkedIn', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='raw_pdfs/')),
                ('email', models.EmailField(max_length=254)),
                ('linkedIn', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PastPapar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=6)),
                ('course_title', models.CharField(max_length=255)),
                ('instructor_name', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField(default=2001, validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(2000)])),
                ('campus', models.CharField(choices=[('ISB', 'Islamabad'), ('LHR', 'Lahore'), ('SWL', 'Sahiwal'), ('abbottabad', 'abbottabad'), ('WAH', 'Wah'), ('attock', 'attock'), ('vehari', 'vehari'), ('virtual', 'virtual')], max_length=55)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('exam_type', models.CharField(choices=[('M', 'Midterm'), ('T', 'Terminal'), ('S1', 'Sessional 1'), ('S2', 'Sessional 2')], max_length=2)),
                ('file', models.FileField(upload_to='pastpapers/')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.contributor')),
            ],
        ),
    ]
