# Generated by Django 4.2.4 on 2023-08-15 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('linkedIn', models.URLField(default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Contribution',
            new_name='Submission',
        ),
        migrations.CreateModel(
            name='PastPapar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=255)),
                ('instructor_name', models.CharField(max_length=255)),
                ('campus', models.CharField(choices=[('ISB', 'Islamabad'), ('LHR', 'Lahore'), ('SWL', 'Sahiwal'), ('abbottabad', 'abbottabad'), ('WAH', 'Wah'), ('attock', 'attock'), ('vehari', 'vehari'), ('virtual', 'virtual')], max_length=55)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('exam_type', models.CharField(choices=[('M', 'Midterm'), ('T', 'Terminal')], max_length=1)),
                ('file', models.FileField(upload_to='pastpapers/')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.contributor')),
            ],
        ),
    ]
