# Generated by Django 4.2.4 on 2023-08-15 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contributor_rename_contribution_submission_pastpapar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpapar',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.contributor'),
        ),
    ]
