# Generated by Django 4.2.4 on 2023-08-20 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_pastpapar_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PastPapar',
            new_name='PastPaper',
        ),
    ]
