# Generated by Django 4.2.4 on 2023-08-16 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_pastpapar_submitted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastpapar',
            name='file',
        ),
    ]
