# Generated by Django 4.2.4 on 2023-08-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_pastpapar_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='submission',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
