# Generated by Django 4.2.4 on 2023-08-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_contributor_email_submission_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='linkedIn',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='submission',
            name='linkedIn',
            field=models.URLField(),
        ),
    ]
