# Generated by Django 4.2.4 on 2023-08-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_contributor_email_alter_contributor_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpapar',
            name='file',
            field=models.FileField(default='temp.txt', upload_to='pastpapers/'),
        ),
    ]
