# Generated by Django 4.2.4 on 2023-08-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_pastpapar_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpapar',
            name='file',
            field=models.FileField(upload_to='pastpapers/'),
        ),
    ]
