name: Build and deploy Frontend of Node.js app to Azure Web App - paperhub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./frontend/past-papers  # Set the default working directory to frontend/past-papers

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: 'v18.16.0' # Use Node.js v18.16.0

      - name: Print current working directory
        run: pwd

      - name: List directory contents
        run: ls -al

      - name: Install dependencies
        run: npm install

      - name: Build the frontend
        run: npm run build

      - name: Create temporary directory
        run: mkdir temp_frontend

      - name: Copy frontend files to the temporary directory
        run: cp -r ./dist/* ./temp_frontend/

      - name: Print contents of the temporary directory
        run: ls -al ./temp_frontend

      - name: Pause for 10 seconds
        run: sleep 10  # Sleep for 10 seconds

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-app
          path: temp_frontend  # Upload the contents of the temporary directory
