name: Build and deploy Frontend of Node.js app to Azure Web App - paperhub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./frontend/past-papers  # Set the default working directory to frontend/past-papers

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: 'v18.16.0' # Use Node.js v18.16.0

      - name: Print current working directory
        run: pwd

      - name: List directory contents
        run: ls -al

      - name: npm install
        run: npm install
        # No need to specify working-directory here, it will use the default

      - name: npm build
        run: npm run build --if-present
        # No need to specify working-directory here, it will use the default

      - name: npm test
        run: npm run test --if-present
        # No need to specify working-directory here, it will use the default

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: frontend-app
          path: .
