# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build, Zip, and Deploy Frontend of Node.js app to Azure Web App - paperhub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend/past-papers  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Zip the build directory
      - name: Zip Release
        working-directory: ./frontend/past-papers  # Set working directory for this step
        run: |
          TheDoctor0/zip-release@0.6.1
          with:
            filename: release.zip
            path: ./dist/*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: frontend-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    defaults:
      run:
        working-directory: ./frontend/past-papers  # Set the default working directory for the deploy job

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: frontend-app

      - name: Deploy frontend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'paperhub'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0CA1F20F535D4E95832381DDD648768C }}
          package: release.zip
