name: Build and deploy Frontend of Node.js app to Azure Web App - paperhub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./frontend/past-papers  # Set the default working directory to frontend/past-papers

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: 'v18.16.0' # Use Node.js v18.16.0

      - name: Print current working directory
        run: pwd

      - name: List directory contents
        run: ls -al

      - name: Pause for 10 seconds
        run: sleep 10  # Sleep for 10 seconds

      - name: Create archive with --ignore-failed-read
        run: tar -czf frontend-app.tar.gz --ignore-failed-read .
        # This command creates a compressed archive of the frontend directory
        # with the --ignore-failed-read option

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-app
          path: frontend-app.tar.gz  # Upload the compressed archive instead of the directory
