name: Build and deploy Frontend of Node.js app to Azure Web App - paperhub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./frontend/past-papers  # Set the default working directory to frontend/past-papers

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: 'v18.16.0' # Use Node.js v18.16.0

      - name: Print current working directory
        run: pwd

      - name: List directory contents
        run: ls -al

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Create temporary directory
        run: mkdir temp_frontend

      - name: Copy frontend files to the temporary directory
        run: cp -r --exclude=temp_frontend ./* ./temp_frontend/

      - name: Pause for 10 seconds
        run: sleep 10  # Sleep for 10 seconds

      - name: Create archive from the temporary directory
        run: tar -czf frontend-app.tar.gz -C temp_frontend/ .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-app
          path: frontend-app.tar.gz  # Upload the compressed archive instead of the directory

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: frontend-app

      - name: Deploy frontend to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'paperhub'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0CA1F20F535D4E95832381DDD648768C }}
          package: $(github.workspace)/frontend-app.tar.gz
