name:  Deploy Frontend to Azure Web App - paperhub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      WORKING_DIRECTORY: ./frontend # Define the working directory environment variable

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install dependencies and build
        run: |
          cd $WORKING_DIRECTORY  # Change to the working directory
          npm install
          npm run build

      # Zip the build directory
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.1
        with:
          filename: release.zip
          directory: ./frontend
          path: dist/* # Use the working directory for the path

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: frontend-app
          path: ./frontend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: frontend-app

      - name: Deploy frontend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "paperhub"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_84F60C82F5A7487DBDC3D41D27334CA3 }}
          package: release.zip
